apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: azuretestprovider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-creds2
      key: creds