apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/a1tan/clusters.git
      revision: HEAD
      directories:
      - path: crossplane/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/a1tan/clusters.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
          automated:
              allowEmpty: true
              prune: true
              selfHeal: true