apiVersion: network.azure.crossplane.io/v1alpha3
kind: Subnet
metadata:
  name: sample-sub
spec:
  resourceGroupNameRef:
    name: sample-rg
  virtualNetworkNameRef:
    name: sample-vn
  properties:
    addressPrefix: 10.2.0.0/24
    serviceEndpoints:
      - service: Microsoft.Sql
  providerConfigRef:
    name: azuretestprovider