apiVersion: azure.jet.crossplane.io/v1alpha2
kind: ResourceGroup
metadata:
  name: terra-sample-rg
spec:
  forProvider:
    location: "West Europe"
    tags:
      provisioner: crossplane
  providerConfigRef:
    name: azuretestprovider