apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: sample-akscluster
  namespace: azure
  labels:
    sample: "true"
spec:
  resourceGroupNameRef:
    name: sample-rg
  vnetSubnetIDRef:
    name: sample-sub
  location: West US 2
  version: "1.19.11"
  nodeCount: 1
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: false
  providerConfigRef:
    name: azuretestprovider
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: sample-akscluster