resources:
  - ../../base
  - namespace.yaml
namespace: azure-dev
namePrefix: dev-
patches:
- path: subnet.yaml
  target:
    kind: Subnet
- path: testcluster.yaml
  target:
    kind: AKSCluster
- path: virtualnetwork.yaml
  target:
    kind: VirtualNetwork
- path: api-management.yaml
  target:
    kind: Management