# $patch: delete
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSCluster
metadata:
  name: dev-sample-akscluster
spec:
  resourceGroupNameRef:
    name: dev-sample-rg
  vnetSubnetIDRef:
    name: dev-sample-sub
  writeConnectionSecretToRef:
    name: dev-sample-akscluster
  location: West Europe
  version: "1.21.9"
